### ISSUE TITLE
[FEATURE]: Can add a plain text view?

### ISSUE THREAD

**Issue by ZSkycat** [Falcion/UNITADE.md#73]
### What the essence of your feature request

Plain text will be rendered as markdown in reading view.
I want it to be displayed as plain text.

In txt file:
```
Steam\userdata\*\*\remote
#Key
```

In reading view:
```
Steam\userdata**\remote
#Key (>> It becomes a nasty tag)
```

### On what OS you want to maintain your request.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Thanks for opening the issue!

This problem occurs because the extension system (which the plugin works on) reads the .TXT file into the .MD text renderer.

There is currently no solution for this issue, so I plan to integrate a full-fledged syntax highlighting system and a "code editor" based on "Monaco Editor" technology, since CM (Codemirrors) has long ceased to support the functionality of its own renderer.

In the near future, I plan to start developing this integration, the progress can be checked in the branch:\
https://github.com/Falcion/UNITADE.md/tree/feature/syntax-highlighting

**Comment by pemre** [comment]
# Rendering "txt", "yml", "csv" and all file types as plain text in Obsidian, using UNITADE

I use a trick to render "txt", "yaml" (yml) and "csv" files as plain text.

## Step 1

I installed UNITADE as usual, then defined txt, yml and csv as extensions:

![image](https://github.com/user-attachments/assets/7750ec2b-a750-4ff8-ae03-078fea66a4c8)

At this point comments in yml files are rendered as H1/2/3 headers which we want to prevent...

## Step 2

Then I created a CSS snippet file, put it under "snippets" folder, and enabled it in Appearance settings:

![image](https://github.com/user-attachments/assets/b3f94c25-2a28-4428-89f7-643d43fff67f)

Here is `snippet.css` for "yml" extension, you can extend it to any other extension you want with copy/pasting the whole rule and replacing "yml" with your extension.  If you know a bit CSS, you can reuse the CSS selectors and make it efficient too:

```css
/* Note: This trick will not work when you have split view */

/* ============================ YML ============================ */

/* IF left menu (mod-left-split) has an active file with "yml" extension */
.mod-left-split:has( .nav-file-title.is-active[data-path$="yml"] )

/* THEN its sibling (mod-root) will have overriden CSS rules */
~ .mod-root .workspace-leaf-content .cm-content * {
    color: var(--code-normal);
    font-size: var(--font-text-size);
    font-family: var(--font-monospace);
    font-weight: normal;
}

/* IF left menu (mod-left-split) has an active file with "yml" extension */
.mod-left-split:has( .nav-file-title.is-active[data-path$="yml"] )

/* THEN its sibling (mod-root) will have overriden CSS rules */
~ .mod-root .workspace-leaf-content .cm-header {
    color: var(--text-accent);
}
```

## End result

This is the result:

![image](https://github.com/user-attachments/assets/7af1a695-9305-47fb-8d70-4df42d299da1)

# Notes:

1. This trick **will not work when you have split view**. I didn't spend much time to make it work to be honest. While working on yml files I don't really need split view. If anyone finds a CSS way to improve it, you're welcome to share 🤗.
2. I didn't test it much, so you may see weird behaviour. I override (cosmetically of course, CSS doesn't change the actual content) almost everything under content section. Use at your own risk.
3. I use **source mode** when I edit yml files. So rendering in classic mode still hides "#" hashtags; I can't handle it with pure CSS (at least didn't check devTools, probably not possible).

**Comment by pemre** [comment]
@ZSkycat for preventing #tags becoming a rounded chip, you can add:

```css
/* IF left menu (mod-left-split) has an active file with "txt" extension */
.mod-left-split:has( .nav-file-title.is-active[data-path$="txt"] )

/* THEN its sibling (mod-root) will have overriden CSS rules */
~ .mod-root .workspace-leaf-content .cm-hashtag {
    padding: 0;
    background: none;
}
```
